server:
  port: 8888

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#spring:
#  cloud:
#    config:
#     server:
#        native:
#          search-locations: classpath:/shared
#  profiles:
#     active: native

spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/coldxiangyu/spring-cloud-base.git
          searchPaths: config/src/main/resources/shared

management.security.enabled: false