server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management.security.enabled: false
# security:
  # user:
    # name: user
    # password: ${REGISTRY_SERVER_PASSWORD:password}
